# Generated by Django 3.1.6 on 2021-07-20 11:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0015_child_oldprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myslider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link_number', models.PositiveIntegerField(default='5')),
                ('URL', models.URLField(max_length=5000)),
                ('slider_number', models.PositiveIntegerField(default='5')),
                ('is_active', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MysSliChild', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Mysection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('secName', models.CharField(default='none', max_length=200)),
                ('details', models.TextField(max_length=1000)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MySecChild', to='products.product')),
            ],
        ),
    ]
