# Generated by Django 3.1.6 on 2021-07-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypages', '0002_myslider_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myslider',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
