# Generated by Django 3.1.6 on 2021-07-20 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_child_oldprice'),
        ('mypages', '0003_auto_20210720_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='myslider',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mysection',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MyChild', to='products.product'),
        ),
    ]
