# Generated by Django 3.2.7 on 2023-08-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_details'),
        ('accounts', '0002_userprofile_product_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='product_favorites',
            field=models.ManyToManyField(blank=True, to='products.Child'),
        ),
    ]
