# Generated by Django 3.1.6 on 2021-07-05 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, max_length=2000)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('photo6', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('photo7', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('photo8', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos_uploaded')),
                ('is_active', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
