# Generated by Django 3.1.6 on 2021-07-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=19),
        ),
    ]
