# Generated by Django 4.0.4 on 2022-05-03 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210723_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='expire',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='security_code',
        ),
    ]
