# Generated by Django 3.1.6 on 2021-07-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210701_1636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
    ]
