# Generated by Django 3.1.6 on 2021-07-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_delete_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='oldPrice',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
