# Generated by Django 3.1.6 on 2021-07-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_child_oldprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=19),
        ),
    ]
