# Generated by Django 4.0.5 on 2022-09-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_delete_new_product_photo10_product_photo3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
